### ISSUE TITLE
g:detectindent_min_indent not respected

### ISSUE THREAD

**Issue by Konfekt** [roryokane/detectindent#13]
At

https://github.com/roryokane/detectindent/blob/master/plugin/detectindent.vim#L118

if `g:detectindent_max_indent` exists and `a:current_indent_width < g:detectindent_min_indent`, then `a:current_indent_width` is not respected.

**Comment by roryokane** [comment]
[The unit test I added to test this bug][new-test] now passes.

[new-test]: https://github.com/roryokane/detectindent/blob/da61569ae9ffb09d1371b1e32c05ce317669ce15/tests/config-options-are-respected.vader#L58-L67

**Comment by Konfekt** [comment]
Thanks for the prompt and good work, the code looks much more sensible now. Hopefully no more `sw=1`!
