### ISSUE TITLE
Allow to see what `DetectIndent` did without executing it again

### ISSUE THREAD

**Issue by blueyed** [roryokane/detectindent#2]
While there is `:verb DetectIndent`, this will process the buffer again.

It would be nice to have `DetectIndentInfo`, which would display the detected/applied settings from the last run.

**Comment by roryokane** [comment]
> This issue might get fixed also by making DetectIndent only remember / set the initial values once, e.g. in a buffer local variable.

DetectIndent already does this. I have done a little refactoring to make that clearer. The buffer’s initial values are [saved in a buffer-local variable `b:detectindent_original_buffer_settings`](https://github.com/roryokane/detectindent/blob/7e7b22cddcc7ed930490d8f7d9b36ac272f4dead/plugin/detectindent.vim#L136-L140), only the first time `:DetectIndent` is run. Those initial values are then [used to build the “Changes from the buffer’s initial settings” message](https://github.com/roryokane/detectindent/blob/7e7b22cddcc7ed930490d8f7d9b36ac272f4dead/plugin/detectindent.vim#L244-L252).

Testing it by hand, it seems to be working properly. If I open a new file and type some three-spaced text in, then run `:verb DetectIndent`, the message includes “tabstop changed from 4 to 3”. If I rerun `:verb DetectIndent` without changing the file, the message still says “tabstop changed from 4 to 3”. And if I change the indentation to two spaces and rerun `:verb DetectIndent`, the message now says “tabstop changed from 4 to 2”. In all messages, DetectIndent remembered that the original value was 4, not 3.

Does that solve your problem?

**Comment by roryokane** [comment]
Since you haven’t replied to say that `:verb DetectIndent` isn’t working for you, I am guessing that my previous post was enough to solve your problem.
